### ISSUE TITLE
wsdl not working

### ISSUE THREAD

**Issue by watta90** [sklose/WeMoWsdl#1]
Hi

Thanks for the wsdl but I don't know if it is not working anymore or if I'm not using it correctly. I have a wemo switch and I can controll it with my phone but when I try to use a soap client to send messages I get an error back. I use this chrome plugin as the soap client 
https://chrome.google.com/webstore/detail/restinsoap-soap-rest-clie/eipdnjedkpcnlmmdfdkgfpljanehloah

This is the request I'm sending:

```
<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:Belkin:service:basicevent:1">
  <x:Header/>
  <x:Body>
    <urn:SetBinaryState>
      <urn:BinaryState>1</urn:BinaryState>
    </urn:SetBinaryState>
  </x:Body>
</x:Envelope>
```

And this is the respons:

```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body>
    <s:Fault>
      <faultcode>s:Client</faultcode>
      <faultstring>UPnPError</faultstring>
      <detail>
        <UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
          <errorCode>-111</errorCode>
          <errorDescription>Invalid Action</errorDescription>
        </UPnPError>
      </detail>
    </s:Fault>
  </s:Body>
</s:Envelope>
```

Any idea of what is wrong?

**Comment by sklose** [comment]
Unfortunately I don't own a WeMo switch anymore to test. I would recommend to try again with http://www.soapui.org/. It auto-generates the request body for you and you only have to put in the values. If that doesn't work either then I would assume Belkin changed the protocol used to communicate with the WeMo.

**Comment by watta90** [comment]
It did actually work with the program you mentioned. Weird that the chrome plugin didn't work, it did also auto generate the request body but maybe some strange headers was also sent from the plugin. 
Thanks!
